# task_app/docker-compose.yml

version: "3.8"

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "4000:4000"
    volumes:
      - ./backend:/app
      - ./frontend/public/screenshot:/frontend/public/screenshot
    environment:
      - NODE_ENV=development
      - PORT=4000
      - MONGODB_URI=your_mongodb_connection_string
      - PUPPETEER_SKIP_CHROMIUM_DOWNLOAD=true
      - PUPPETEER_EXECUTABLE_PATH=/usr/bin/google-chrome-stable
