FROM ghcr.io/puppeteer/puppeteer:22.11.1 

ENV PUPPETEER_SKIP_CHROMIUM_DOWNLOAD=true \PUPPETEER_EXECUTABLE_PATH=/usr/bin/google-chrome-stable
WORKDIR /app

COPY package*.json ./
RUN npm ci
RUN mkdir -p ../frontend/public/screenshot
COPY . .
CMD [ "node", "index.js" ]